version: '3.8'
services:
  ppe_detection:
    build: ./ppe_detection_model
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '6.0'
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=0  # Limit to one GPU if needed

  face_recognition:
    build: ./face_recognition_model
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '6.0'
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=0  # Limit to one GPU if needed

volumes:
  data:
